language: node_js
node_js:
  - "10.15.3"

cache:
  paths:
    - node_modules/

before_script:
  - npm  i
  - npm run build

script:
  - npm run test

after_success:
  - npm run typedoc

notifications:
  slack: hillwall:mEooxj82YSeXdwrnoLlsWahJ
